const specialties = [
  "Pedreiro",
  "Eletricista",
  "Encanador",
  "Jardineiro",
  "Faxineira",
  "Diarista",
  "Pintor",
  "Carpinteiro",
  "Marceneiro",
  "Montador de Móveis",
  "Instalador de Câmeras",
  "Técnico de Informática",
  "Professor",
  "Mecânico",
  "Chaveiro",
  "Encanador Industrial",
  "Técnico em Ar Condicionado",
  "Motorista",
  "Auxiliar de Serviços Gerais",
  "Segurança",
  "Fotógrafo",
  "Design Gráfico",
  "Programador",
  "Consultor",
  "Eletricista Automotivo",
  "Cabeleireiro",
  "Manicure",
  "Pedicure",
  "Assistente Administrativo",
  "Assistente Financeiro",
  "Reparador de Eletrodomésticos",
  "Técnico em Redes",
  "Técnico em Informática",
  "Técnico em Telecomunicações",
  "Engenheiro Civil",
  "Arquiteto",
  "Veterinário",
  "Nutricionista",
  "Personal Trainer",
  "Psicólogo",
  "Advogado",
  "Contador",
  "Consultor de Marketing",
  "Jornalista",
  "Redator",
  "Tradutor",
  "Motorista de Aplicativo",
  "Esteticista",
  "Mecânico de Bicicletas",
  "Eletricista Residencial",
  "Eletricista Predial",
  "Serralheiro",
  "Montador de Móveis",
  "Técnico em Segurança do Trabalho",
  "Técnico em Meio Ambiente",
  "Assistente Social",
  "Técnico em Saúde Bucal",
  "Professor de Inglês",
  "Professor de Matemática",
 "Professor de Física",
  "Professor de Música",
  "Técnico em Logística",
  "Técnico em Automação",
  "Engenheiro Eletricista",
  "Engenheiro Mecânico",
];

export default specialties;
